error_log /data/nginx/error.log;
pid /data/nginx/process.pid;

events {
    worker_connections 1024;
}

http {
    access_log /data/nginx/access.log;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    client_body_temp_path /data/nginx/client_body_temp;
    proxy_temp_path /data/nginx/proxy_temp;

    include /data/nginx/server.conf;
}
